
#include "shared.h"

#define TASMOTA_DEVICEGROUPS_HEADER "TASMOTA_DGR"

#define DGR_ITEM_EOL				0
#define DGR_ITEM_STATUS				1
#define DGR_ITEM_FLAGS				2
#define DGR_ITEM_LIGHT_FADE			3
#define DGR_ITEM_LIGHT_SPEED		4
#define DGR_ITEM_LIGHT_BRI			5
#define DGR_ITEM_LIGHT_SCHEME		6
#define DGR_ITEM_LIGHT_FIXED_COLOR	7
#define DGR_ITEM_BRI_PRESET_LOW		8
#define DGR_ITEM_BRI_PRESET_HIGH	9
#define DGR_ITEM_BRI_POWER_ON		10
#define DGR_ITEM_LAST_8BIT			11
#define DGR_ITEM_MAX_8BIT			63

#define DGR_ITEM_LAST_16BIT			64
#define DGR_ITEM_MAX_16BIT			127

#define DGR_ITEM_POWER				128
#define DGR_ITEM_NO_STATUS_SHARE	129
#define DGR_ITEM_LAST_32BIT			130
#define DGR_ITEM_MAX_32BIT			191

#define DGR_ITEM_EVENT				192
#define DGR_ITEM_COMMAND			193
#define DGR_ITEM_LAST_STRING		194
#define DGR_ITEM_MAX_STRING			223

#define DGR_ITEM_LIGHT_CHANNELS		224
#define DGR_ITEM_LAST_ARRAY			225
#define DGR_ITEM_MAX_ARRAY			255



